name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    env:
      IMAGE_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: docker build -t fastapi-app .

      - name: Tag Image
        run: |
          docker tag fastapi-app:latest $IMAGE_URI:${{ github.sha }}
          docker tag fastapi-app:latest $IMAGE_URI:latest

      - name: Push Image
        run: |
          docker push $IMAGE_URI:${{ github.sha }}
          docker push $IMAGE_URI:latest

      - name: Fill ECS Task Definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: deploy/url-shorter-task.json
          container-name: url-shorter-container
          image: ${{ env.IMAGE_URI }}:${{ github.sha }}

      - name: Debug Image URI
        run: echo "$IMAGE_URI:${{ github.sha }}"

      - name: Print rendered task definition
        run: cat ${{ steps.task-def.outputs.task-definition }}

      - name: Deploy ECS Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: fastapi-service
          cluster: fastapi-cluster
          wait-for-service-stability: true